# Generated by Django 5.2.13 on 2026-04-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meherloom", "0002_product_size_guide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="adapter_key",
            field=models.CharField(
                choices=[
                    ("generic", "Generic JSON-LD scraper"),
                    ("shopify", "Shopify product scraper"),
                    ("sapphire", "SAPPHIRE product scraper"),
                    ("agha_noor", "Agha Noor product scraper"),
                ],
                default="generic",
                max_length=50,
            ),
        ),
    ]
